SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE `bookrecord` (
  `bookid` int(11) NOT NULL AUTO_INCREMENT,
  `bid` int(11) NOT NULL,
  `issued` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`bookid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=16 ;

CREATE TABLE `books` (
  `bid` int(11) NOT NULL AUTO_INCREMENT,
  `bname` varchar(100) DEFAULT NULL,
  `bauth` varchar(100) DEFAULT NULL,
  `bcopies` int(11) NOT NULL DEFAULT '1',
  `bpub` varchar(40) DEFAULT NULL,
  `bsup` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`bid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

CREATE TABLE `members` (
  `mid` int(11) NOT NULL AUTO_INCREMENT,
  `mname` varchar(100) DEFAULT NULL,
  `mph` varchar(12) DEFAULT NULL,
  `mbook` tinyint(1) NOT NULL DEFAULT '0',
  `mad` varchar(250) DEFAULT NULL,
  `mdoj` date DEFAULT NULL,
  PRIMARY KEY (`mid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=9 ;

CREATE TABLE `register` (
  `iid` int(11) NOT NULL AUTO_INCREMENT,
  `bookid` int(11) NOT NULL,
  `mid` int(11) NOT NULL,
  `idate` date NOT NULL,
  `ireturn` date DEFAULT NULL,
  `remarks` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`iid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=17 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
